name: main

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  test:
    name: run unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/test'
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN }}'

      - run: 'Found it!'
        if: steps.check.outputs.triggered == 'true'
