name: main

on:
  pull_request:
    types: [opened, closed]
  issue_comment:
    types: [created]

jobs:
  test:
    name: run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/run-test'
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN }}'

      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'

      - name: Delete env when pr is merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
